export const Categories = [
    "Fiction",
    "Non-Fiction",
    "Science",
    "Technology",
    "Mystery",
    "Thriller",
    "Romance",
    "Horror",
    "Fantasy",
    "Adventure",
    "Biography",
    "Autobiography",
    "Self-Help",
    "Health",
    "History",
    "Travel",
    "Guide",
    "Children",
    "Comics",
    "Graphic Novels",
    "Poetry",
    "Drama",
    "Action",
    "Suspense",
    "Dystopian",
    "Science Fiction",
    "Humor",
    "Satire",
    "Anthology",
    "Encyclopedias",
    "Dictionaries",
    "Cookbooks",
    "Diaries",
    "Journals",
    "Prayer Books",
    "Series",
    "Trilogy",
    "Guidebook",
    "Textbook",
    "Manual",
    "Reference",
    "Almanac",
    "Atlas",
    "Dictionary",
    "Encyclopedia",
    "Handbook",
    "Thesaurus",
    "Bible",
    "Quran",
    "Vedas",
    "Upanishads",
    "Puranas",
    "Ramayana",
    "Mahabharata",
    "Bhagavad Gita",
    "Yoga Sutras",
    "Sutras",
    "Agamas",
    "Tantras",
    "Samhitas",
    "Brahmanas",
  
]